Added nuget.config to root of the repo to help dotnet restore run wit…
Azure-Samples/azure-iot-samples-csharp pull request #239
Opened 2021-09-19 19:56 UTC by OrrinEdenfield

See discussion on this PR: https://github.com/Azure-Samples/azure-iot-samples-csharp/pull/238

2021-09-20 17:07 UTC, drwill-ms approved these changes

2021-09-20 17:07 UTC, drwill-ms commented
/azp run

2021-09-20 17:11 UTC, drwill-ms commented on nuget.config
> +    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
Pipeline indicated a need for a line before this:

> nuget.config - Missing <clear/> statement.


```xml
    <clear />
```

2021-09-21 04:21 UTC, drwill-ms requested changes
See my code comment.

2021-09-21 06:14 UTC, OrrinEdenfield commented
Line added to file.

2021-09-21 21:46 UTC, drwill-ms commented
/azp run

2021-09-21 21:46 UTC, drwill-ms approved these changes

2021-09-22 00:00 UTC, merged